// livre-data.js — métadonnées canoniques des 27 chapitres
// Source : frontmatter YAML des fichiers livre/chapitres/ch{NN}-*.md
// Consommé par livre-app.js (reader, breadcrumb, prev/next) et utilisable côté Python à terme.

window.LIVRE_DATA = {
  titre: "Anatomie d'une IA agentique",
  sous_titre: "Le livre — 27 chapitres, 4 actes, ~187 000 mots",
  statut: "v1 — 25/27 chapitres livrés (ch.12 ADK et ch.14 assistants de code en rédaction ; Prologue et Épilogue à venir)",
  date: "2026-06-04",
  actes: [
    {
      num: "I",
      slug: "acte-1",
      titre: "Les moteurs",
      sous_titre: "Couches du dessous de la pile. Avant la boucle, le modèle. Avant la conversation, un tirage probabiliste.",
      lecteur: "Expert data · FinOps · acheteur infra/cloud · sponsor IA technique",
      infographie: "images/20260601-acte1-moteurs-infographie.svg",
      chapitres: [1, 2, 3, 4, 5, 6],
    },
    {
      num: "II",
      slug: "acte-2",
      titre: "La boucle",
      sous_titre: "Anneaux 01-04 (boucle, outils, contexte, patterns), jusqu'aux kits qui servent à la builder. C'est ici que se gagne ou se perd le ROI.",
      lecteur: "Agent engineer · tech lead · architecte · platform engineer",
      infographie: "images/20260601-acte2-boucle-infographie.svg",
      chapitres: [7, 8, 9, 10, 11, 12],
    },
    {
      num: "III",
      slug: "acte-3",
      titre: "Les interfaces",
      sous_titre: "Anneau 05 + surfaces. C'est par là que l'utilisateur final touche l'agent — du régime d'accès à l'assistant de code, jusqu'au protocole qui le câble aux outils.",
      lecteur: "PM · designer · intégrateur · architecte plateforme · CDO sectoriel",
      infographie: "images/20260601-acte3-interfaces-infographie.svg",
      chapitres: [13, 14, 15, 16, 17, 18],
    },
    {
      num: "IV",
      slug: "acte-4",
      titre: "Mesures et garde-fous",
      sous_titre: "Anneaux 06-09 (guardrails, observabilité, runtime, governance). C'est ici que se gagne ou se perd la confiance du décideur.",
      lecteur: "Décideur · sponsor · RSSI · DPO · FinOps · CDO · CRO/COO banque",
      infographie: "images/20260601-acte4-mesures-garde-fous-infographie.svg",
      chapitres: [19, 20, 21, 22, 23, 24, 25, 26, 27],
    },
  ],
  chapitres: {
    1:  { slug: "ch01-coeur-stochastique",                  titre: "Le cœur stochastique",                                         acte: "I",   mots: 4760,  gabarit: "encart" },
    2:  { slug: "ch02-modeles-raisonnement",                titre: "Les modèles de raisonnement et la seconde courbe de scaling",  acte: "I",   mots: 7630,  gabarit: "standard" },
    3:  { slug: "ch03-process-reward-models",               titre: "La couche notateur cachée (Process Reward Models)",            acte: "I",   mots: 7540,  gabarit: "standard" },
    4:  { slug: "ch04-decode-speculative",                  titre: "Décode spéculative et la course au token/sec",                 acte: "I",   mots: 6590,  gabarit: "standard" },
    5:  { slug: "ch05-economie-inference",                  titre: "L'économie unitaire de l'inférence (et son angle mort)",       acte: "I",   mots: 7590,  gabarit: "standard" },
    6:  { slug: "ch06-world-models",                        titre: "Bordure : world models et physique apprise",                   acte: "I",   mots: 3340,  gabarit: "encart" },
    7:  { slug: "ch07-boucle-agentique",                    titre: "Reason · Act · Observe : le harness et ce qu'il enveloppe",    acte: "II",  mots: 9510,  gabarit: "charnière" },
    8:  { slug: "ch08-outils-de-lagent",                    titre: "Les outils (les mains de l'agent)",                            acte: "II",  mots: 6140,  gabarit: "standard" },
    9:  { slug: "ch09-memoire-agentique",                   titre: "Mémoire agentique : 4 piliers, 6 opérations, 5 architectures", acte: "II",  mots: 6900,  gabarit: "standard" },
    10: { slug: "ch10-compaction",                          titre: "Compaction et oubli stratégique",                              acte: "II",  mots: 4880,  gabarit: "standard" },
    11: { slug: "ch11-patterns-orchestration",              titre: "Patterns canoniques et orchestration multi-agents",            acte: "II",  mots: 7810,  gabarit: "charnière" },
    12: { slug: "ch12-adk-frameworks",                      titre: "Construire la boucle : SDK, ADK et frameworks d'agents",       acte: "II",  mots: 5200,  gabarit: "standard" },
    13: { slug: "ch13-surfaces-agentiques",                 titre: "Surfaces agentiques : quatre régimes d'accès",                 acte: "III", mots: 10370, gabarit: "standard" },
    14: { slug: "ch14-assistants-de-code",                  titre: "Assistants de code : Claude Code, Copilot, Codex, Antigravity",acte: "III", mots: 5400,  gabarit: "standard" },
    15: { slug: "ch15-mcp-plateforme",                      titre: "MCP, le HTTP des agents",                                      acte: "III", mots: 5550,  gabarit: "standard" },
    16: { slug: "ch16-mcp-securite",                        titre: "Sécurité MCP : dix vecteurs × dix patterns",                   acte: "III", mots: 5570,  gabarit: "standard" },
    17: { slug: "ch17-computer-use",                        titre: "Computer use : le régime extrême",                             acte: "III", mots: 7530,  gabarit: "standard" },
    18: { slug: "ch18-analytics-agentique-banque",          titre: "Analytics agentique : la stack data + IA en sectoriel régulé", acte: "III", mots: 10800, gabarit: "standard" },
    19: { slug: "ch19-evaluation-benchmarks",               titre: "Évaluer un agent (et débunker les leaderboards)",              acte: "IV",  mots: 11050, gabarit: "charnière" },
    20: { slug: "ch20-observabilite-cognitive-audit-trail", titre: "Observabilité agentique et cognitive audit trail",             acte: "IV",  mots: 6000,  gabarit: "standard" },
    21: { slug: "ch21-gardefous-securite-globale",          titre: "Garde-fous, jailbreaking et sécurité globale",                 acte: "IV",  mots: 6720,  gabarit: "charnière" },
    22: { slug: "ch22-runtime-manage",                      titre: "Runtime managé et déploiement",                                acte: "IV",  mots: 6240,  gabarit: "standard" },
    23: { slug: "ch23-roi-paradoxe-agentique",              titre: "Mesurer le ROI (et le paradoxe agentique)",                    acte: "IV",  mots: 8530,  gabarit: "charnière" },
    24: { slug: "ch24-ia-frugale",                          titre: "Externalité énergétique : IA frugale",                         acte: "IV",  mots: 8120,  gabarit: "standard" },
    25: { slug: "ch25-gouvernance-ai-act",                  titre: "Gouvernance : AI Act, banque, machine unlearning",             acte: "IV",  mots: 9300,  gabarit: "standard" },
    26: { slug: "ch26-ia-et-travail",                       titre: "Société : IA et travail",                                      acte: "IV",  mots: 10115, gabarit: "standard" },
    27: { slug: "ch27-proces-musk-altman",                  titre: "Politique : procès Musk v. Altman",                            acte: "IV",  mots: 7190,  gabarit: "encart" },
  },
};
